package models

var StorageConfigTemplates = map[string][]ConfigTemplate{
	"local": {
		{
			Name:        "存储路径",
			KeyName:     "base_path",
			Type:        "string",
			Required:    true,
			Description: "本地存储的基础路径",
			Default:     "uploads/files",
		},
		{
			Name:        "缩略图路径",
			KeyName:     "thumbnail_path",
			Type:        "string",
			Required:    true,
			Description: "文件缩略图存储路径",
			Default:     "uploads/thumbnails",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "自定义访问域名",
		},
	},
	"oss": {
		{
			Name:        "地域 (Region)",
			KeyName:     "region",
			Type:        "string",
			Required:    true,
			Description: "如 oss-cn-hangzhou，通常可从 Endpoint 推导",
		},
		{
			Name:        "存储空间（Bucket）",
			KeyName:     "bucket",
			Type:        "string",
			Required:    true,
			Description: "OSS 存储空间名称（Bucket）",
		},
		{
			Name:        "Endpoint（地域节点）",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    true,
			Description: "如 https://oss-cn-hangzhou.aliyuncs.com 或自定义 Endpoint",
		},
		{
			Name:        "AccessKey ID",
			KeyName:     "access_key",
			Type:        "string",
			Required:    true,
			Description: "阿里云访问密钥 AccessKey ID",
		},
		{
			Name:        "AccessKey Secret",
			KeyName:     "secret_key",
			Type:        "password",
			Required:    true,
			Description: "阿里云访问密钥 AccessKey Secret",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "自定义访问域名",
		},
		{
			Name:        "存储类型",
			KeyName:     "storage_class",
			Type:        "string",
			Required:    false,
			Description: "存储类型：STANDARD/IA/ARCHIVE/COLD_ARCHIVE",
			Options:     []string{"STANDARD", "IA", "ARCHIVE", "COLD_ARCHIVE"},
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用HTTPS",
			Default:     "true",
		},
		{
			Name:        "隐藏远程 URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程URL，只显示代理URL",
			Default:     "false",
		},
	},
	"s3": {
		{
			Name:        "地域 (Region)",
			KeyName:     "region",
			Type:        "string",
			Required:    true,
			Description: "如 us-east-1，AWS S3 必填；兼容端点也建议填写",
			Default:     "us-east-1",
		},
		{
			Name:        "存储桶（Bucket）",
			KeyName:     "bucket",
			Type:        "string",
			Required:    true,
			Description: "S3 存储桶名称",
		},
		{
			Name:        "Endpoint（可选）",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    false,
			Description: "兼容 S3 的自定义端点（如 MinIO、私有云）；AWS 可留空",
		},
		{
			Name:        "Access Key",
			KeyName:     "access_key",
			Type:        "string",
			Required:    true,
			Description: "访问密钥 Access Key",
		},
		{
			Name:        "Secret Key",
			KeyName:     "secret_key",
			Type:        "password",
			Required:    true,
			Description: "访问密钥 Secret Key",
		},
		{
			Name:        "自定义域名（可选）",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "外链/加速域名，优先于 Endpoint",
		},
		{
			Name:        "路径样式（host/bucket/key）",
			KeyName:     "use_path_style",
			Type:        "bool",
			Required:    false,
			Description: "兼容端点常需开启路径样式；AWS 官方默认虚拟主机样式",
			Default:     "false",
		},
		{
			Name:        "访问控制（可选）",
			KeyName:     "access_control",
			Type:        "string",
			Required:    false,
			Description: "对象 ACL：public-read/private（多数情况建议用桶策略）",
			Options:     []string{"public-read", "private"},
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用 HTTPS",
			Default:     "true",
		},
		{
			Name:        "隐藏远程 URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程 URL，只显示代理 URL",
			Default:     "false",
		},
	},
	"cos": {
		{
			Name:        "地域 (Region)",
			KeyName:     "region",
			Type:        "string",
			Required:    true,
			Description: "如 ap-shanghai",
		},
		{
			Name:        "存储桶（Bucket）",
			KeyName:     "bucket",
			Type:        "string",
			Required:    true,
			Description: "COS 存储桶名称，形如 bucketname-APPID",
		},
		{
			Name:        "SecretId",
			KeyName:     "secret_id",
			Type:        "string",
			Required:    true,
			Description: "腾讯云 API 密钥 SecretId",
		},
		{
			Name:        "SecretKey",
			KeyName:     "secret_key",
			Type:        "password",
			Required:    true,
			Description: "腾讯云 API 密钥 SecretKey",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "自定义访问域名",
		},
		{
			Name:        "访问域名（可选）",
			KeyName:     "domain",
			Type:        "string",
			Required:    false,
			Description: "COS 专用访问域名（可选）",
		},
		{
			Name:        "存储类型",
			KeyName:     "storage_class",
			Type:        "string",
			Required:    false,
			Description: "存储类型：STANDARD/MAZ_STANDARD/STANDARD_IA/MAZ_STANDARD_IA/INTELLIGENT_TIERING/MAZ_INTELLIGENT_TIERING/ARCHIVE/DEEP_ARCHIVE",
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用HTTPS",
		},
		{
			Name:        "隐藏远程 URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程URL，只显示代理URL",
		},
	},
	"qiniu": {
		{
			Name:        "地域 (Region)",
			KeyName:     "region",
			Type:        "string",
			Required:    false,
			Description: "S3 兼容 Region（与 Endpoint 匹配，可留空）",
		},
		{
			Name:        "存储桶（Bucket）",
			KeyName:     "bucket",
			Type:        "string",
			Required:    true,
			Description: "七牛云 Kodo 存储桶名称",
		},
		{
			Name:        "Endpoint（S3 兼容）",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    true,
			Description: "S3 兼容 API 终结点，如 https://s3-cn-east-1.qiniucs.com",
		},
		{
			Name:        "AccessKey",
			KeyName:     "access_key",
			Type:        "string",
			Required:    true,
			Description: "七牛云 AccessKey",
		},
		{
			Name:        "SecretKey",
			KeyName:     "secret_key",
			Type:        "password",
			Required:    true,
			Description: "七牛云 SecretKey",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "外链域名或自定义加速域名",
		},
		{
			Name:        "路径样式（domain/bucket/key）",
			KeyName:     "use_path_style",
			Type:        "bool",
			Required:    false,
			Description: "部分自定义域名需在路径前带上 bucket，开启后生成 domain/bucket/key",
			Default:     "false",
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用 HTTPS",
			Default:     "true",
		},
		{
			Name:        "隐藏远程 URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程 URL，只显示代理 URL",
			Default:     "false",
		},
	},
	"upyun": {
		{
			Name:        "服务名（Space/Service）",
			KeyName:     "service",
			Type:        "string",
			Required:    true,
			Description: "又拍云服务名（空间名）",
		},
		{
			Name:        "操作员名（Operator）",
			KeyName:     "operator",
			Type:        "string",
			Required:    true,
			Description: "又拍云操作员用户名",
		},
		{
			Name:        "操作员密码（Password）",
			KeyName:     "password",
			Type:        "password",
			Required:    true,
			Description: "用于计算签名，仅服务端存储",
		},
		{
			Name:        "Endpoint",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    true,
			Description: "REST API 端点，默认 https://v0.api.upyun.com",
			Default:     "https://v0.api.upyun.com",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "外链/加速域名，直链访问时使用",
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用 HTTPS",
			Default:     "true",
		},
		{
			Name:        "隐藏远程 URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程 URL，仅走系统代理",
			Default:     "false",
		},
	},
	"minio": {
		{
			Name:        "存储桶（Bucket）",
			KeyName:     "bucket",
			Type:        "string",
			Required:    true,
			Description: "MinIO 存储桶名称",
		},
		{
			Name:        "Endpoint（端点地址）",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    true,
			Description: "MinIO 服务端点，如 https://minio.example.com 或 http://192.168.1.100:9000",
		},
		{
			Name:        "Access Key",
			KeyName:     "access_key",
			Type:        "string",
			Required:    true,
			Description: "MinIO 访问密钥 Access Key",
		},
		{
			Name:        "Secret Key",
			KeyName:     "secret_key",
			Type:        "password",
			Required:    true,
			Description: "MinIO 访问密钥 Secret Key",
		},
		{
			Name:        "地域（Region）",
			KeyName:     "region",
			Type:        "string",
			Required:    false,
			Description: "地域设置（某些兼容存储需要），默认 us-east-1",
			Default:     "us-east-1",
		},
		{
			Name:        "自定义域名（可选）",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "外链/加速域名，优先于 Endpoint 生成访问 URL",
		},
		{
			Name:        "访问控制（可选）",
			KeyName:     "access_control",
			Type:        "string",
			Required:    false,
			Description: "访问控制：public-read（公开读取）或 private（私有，使用签名 URL）",
			Options:     []string{"public-read", "private"},
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用 HTTPS（如果 Endpoint 已包含协议则自动检测）",
			Default:     "true",
		},
		{
			Name:        "隐藏远程 URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程 URL，只显示代理 URL",
			Default:     "false",
		},
	},
	"r2": {
		{
			Name:        "区域",
			KeyName:     "region",
			Type:        "string",
			Required:    false,
			Description: "通常填写 auto（R2 基于 Endpoint 工作）",
			Default:     "auto",
		},
		{
			Name:        "存储桶",
			KeyName:     "bucket",
			Type:        "string",
			Required:    true,
			Description: "R2 存储桶名称（Bucket Name）",
		},
		{
			Name:        "Endpoint",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    true,
			Description: "R2 S3 终结点，例如 https://<accountid>.r2.cloudflarestorage.com 或管辖区特定终结点",
		},
		{
			Name:        "访问密钥 ID",
			KeyName:     "access_key",
			Type:        "string",
			Required:    true,
			Description: "Cloudflare R2 访问密钥 ID（Access Key ID）",
		},
		{
			Name:        "机密访问密钥",
			KeyName:     "secret_key",
			Type:        "password",
			Required:    true,
			Description: "Cloudflare R2 机密访问密钥（Secret Access Key）",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "可选：r2.dev 公共域名或自定义加速域名（公开直链时填写）",
		},
		{
			Name:        "使用HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用 HTTPS",
			Default:     "true",
		},
		{
			Name:        "隐藏远程URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程 URL，仅显示代理 URL（私有访问时建议开启）",
			Default:     "false",
		},
	},
	"rainyun": {
		{
			Name:        "区域",
			KeyName:     "region",
			Type:        "string",
			Required:    true,
			Description: "雨云区域，固定为rainyun",
			Default:     "rainyun",
		},
		{
			Name:        "存储桶",
			KeyName:     "bucket",
			Type:        "string",
			Required:    true,
			Description: "雨云对象存储桶名称",
		},
		{
			Name:        "Endpoint（API 端点）",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    true,
			Description: "雨云对象存储 API 端点",
			Default:     "https://cn-sy1.rains3.com",
		},
		{
			Name:        "AccessKey",
			KeyName:     "access_key",
			Type:        "string",
			Required:    true,
			Description: "雨云对象存储 AccessKey",
		},
		{
			Name:        "SecretKey",
			KeyName:     "secret_key",
			Type:        "password",
			Required:    true,
			Description: "雨云对象存储 SecretKey",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "自定义访问域名",
		},
		{
			Name:        "存储类型",
			KeyName:     "storage_class",
			Type:        "string",
			Required:    false,
			Description: "存储类型：STANDARD/STANDARD_IA/GLACIER/DEEP_ARCHIVE",
			Options:     []string{"STANDARD", "STANDARD_IA", "GLACIER", "DEEP_ARCHIVE"},
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用 HTTPS",
			Default:     "true",
		},
		{
			Name:        "隐藏远程 URL",
			KeyName:     "hide_remote_url",
			Type:        "bool",
			Required:    false,
			Description: "是否隐藏远程 URL，只显示代理 URL",
			Default:     "false",
		},
	},
	"webdav": {
		{
			Name:        "服务器地址（Endpoint）",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    true,
			Description: "WebDAV 服务器地址，如 https://dav.example.com 或 http://192.168.1.100:8080",
		},
		{
			Name:        "用户名（Username）",
			KeyName:     "username",
			Type:        "string",
			Required:    true,
			Description: "WebDAV 服务器用户名",
		},
		{
			Name:        "密码（Password）",
			KeyName:     "password",
			Type:        "password",
			Required:    true,
			Description: "WebDAV 服务器密码",
		},
		{
			Name:        "根路径（Root Path）",
			KeyName:     "root_path",
			Type:        "string",
			Required:    false,
			Description: "文件存储的根路径，如 /pixelpunk/ 或 /files/",
			Default:     "/",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "自定义访问域名，用于生成文件外链地址",
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用 HTTPS 协议",
			Default:     "true",
		},
		{
			Name:        "允许直链访问",
			KeyName:     "allow_direct",
			Type:        "bool",
			Required:    false,
			Description: "是否允许直接访问远程 URL（关闭则仅通过系统代理访问）",
			Default:     "false",
		},
		{
			Name:        "自动创建目录",
			KeyName:     "mkdir",
			Type:        "bool",
			Required:    false,
			Description: "上传文件时是否自动创建不存在的目录",
			Default:     "true",
		},
	},
	"azureblob": {
		{
			Name:        "存储账户名（Account Name）",
			KeyName:     "account_name",
			Type:        "string",
			Required:    true,
			Description: "Azure 存储账户名称",
		},
		{
			Name:        "访问密钥（Account Key）",
			KeyName:     "account_key",
			Type:        "password",
			Required:    true,
			Description: "Azure 存储账户访问密钥（Base64 编码）",
		},
		{
			Name:        "容器名称（Container）",
			KeyName:     "container",
			Type:        "string",
			Required:    true,
			Description: "Azure Blob 存储容器名称",
		},
		{
			Name:        "端点地址（Endpoint）",
			KeyName:     "endpoint",
			Type:        "string",
			Required:    false,
			Description: "自定义端点地址，默认使用 https://{account_name}.blob.core.windows.net",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "自定义访问域名",
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "是否强制使用 HTTPS",
			Default:     "true",
		},
		{
			Name:        "访问控制（Access Control）",
			KeyName:     "access_control",
			Type:        "string",
			Required:    false,
			Description: "访问控制类型：public-read（公开读取）或 private（私有，使用 SAS 签名）",
			Options:     []string{"public-read", "private"},
		},
	},
	"sftp": {
		{
			Name:        "主机地址（Host）",
			KeyName:     "host",
			Type:        "string",
			Required:    true,
			Description: "SFTP 服务器主机地址或 IP",
		},
		{
			Name:        "端口（Port）",
			KeyName:     "port",
			Type:        "string",
			Required:    false,
			Description: "SFTP 服务器端口",
			Default:     "22",
		},
		{
			Name:        "用户名（Username）",
			KeyName:     "username",
			Type:        "string",
			Required:    true,
			Description: "SFTP 登录用户名",
		},
		{
			Name:        "密码（Password）",
			KeyName:     "password",
			Type:        "password",
			Required:    false,
			Description: "SFTP 登录密码（与私钥二选一）",
		},
		{
			Name:        "私钥（Private Key）",
			KeyName:     "private_key",
			Type:        "password",
			Required:    false,
			Description: "SSH 私钥内容（PEM 格式，与密码二选一）",
		},
		{
			Name:        "私钥密码（Passphrase）",
			KeyName:     "passphrase",
			Type:        "password",
			Required:    false,
			Description: "私钥的解密密码（如果私钥有加密）",
		},
		{
			Name:        "根路径（Root Path）",
			KeyName:     "root_path",
			Type:        "string",
			Required:    false,
			Description: "文件存储的根路径",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "自定义访问域名，用于生成文件外链地址",
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "生成外链时是否使用 HTTPS 协议",
			Default:     "true",
		},
		{
			Name:        "允许直链访问",
			KeyName:     "allow_direct",
			Type:        "bool",
			Required:    false,
			Description: "是否允许直接访问远程 URL（关闭则仅通过系统代理访问）",
			Default:     "false",
		},
		{
			Name:        "自动创建目录",
			KeyName:     "mkdir",
			Type:        "bool",
			Required:    false,
			Description: "上传文件时是否自动创建不存在的目录",
			Default:     "true",
		},
	},
	"ftp": {
		{
			Name:        "主机地址（Host）",
			KeyName:     "host",
			Type:        "string",
			Required:    true,
			Description: "FTP 服务器主机地址或 IP",
		},
		{
			Name:        "端口（Port）",
			KeyName:     "port",
			Type:        "string",
			Required:    false,
			Description: "FTP 服务器端口（标准 FTP: 21，隐式 FTPS: 990）",
			Default:     "21",
		},
		{
			Name:        "用户名（Username）",
			KeyName:     "username",
			Type:        "string",
			Required:    false,
			Description: "FTP 登录用户名",
			Default:     "anonymous",
		},
		{
			Name:        "密码（Password）",
			KeyName:     "password",
			Type:        "password",
			Required:    false,
			Description: "FTP 登录密码",
			Default:     "anonymous@",
		},
		{
			Name:        "根路径（Root Path）",
			KeyName:     "root_path",
			Type:        "string",
			Required:    false,
			Description: "文件存储的根路径",
		},
		{
			Name:        "自定义域名",
			KeyName:     "custom_domain",
			Type:        "string",
			Required:    false,
			Description: "自定义访问域名，用于生成文件外链地址",
		},
		{
			Name:        "使用 HTTPS",
			KeyName:     "use_https",
			Type:        "bool",
			Required:    false,
			Description: "生成外链时是否使用 HTTPS 协议",
			Default:     "true",
		},
		{
			Name:        "允许直链访问",
			KeyName:     "allow_direct",
			Type:        "bool",
			Required:    false,
			Description: "是否允许直接访问远程 URL（关闭则仅通过系统代理访问）",
			Default:     "false",
		},
		{
			Name:        "自动创建目录",
			KeyName:     "mkdir",
			Type:        "bool",
			Required:    false,
			Description: "上传文件时是否自动创建不存在的目录",
			Default:     "true",
		},
		{
			Name:        "启用 TLS/SSL（FTPS）",
			KeyName:     "use_tls",
			Type:        "bool",
			Required:    false,
			Description: "是否启用 FTPS（FTP over TLS/SSL）",
			Default:     "false",
		},
		{
			Name:        "TLS 模式",
			KeyName:     "tls_mode",
			Type:        "string",
			Required:    false,
			Description: "TLS 模式：explicit（显式 TLS，端口 21）或 implicit（隐式 TLS，端口 990）",
			Options:     []string{"explicit", "implicit"},
			Default:     "explicit",
		},
		{
			Name:        "跳过 TLS 证书验证",
			KeyName:     "tls_skip_verify",
			Type:        "bool",
			Required:    false,
			Description: "是否跳过 TLS 证书验证（仅测试环境使用，生产环境不推荐）",
			Default:     "false",
		},
		{
			Name:        "服务器名称（SNI）",
			KeyName:     "server_name",
			Type:        "string",
			Required:    false,
			Description: "TLS SNI 主机名或证书校验名称（默认使用 host）",
		},
	},
}
